export const testIds = {
  main: "main",
  header: "header",
  headerContent: "headerContent",
  modal: "modal",
  modalHeader: "modalHeader",
  modalCancel: "modalCancel",
  modalClose: "modalClose",
  modalContent: "modalContent",
  modalConfirm: "modalConfirm",
  modalActions: "modalActions",
  skillPath: "skillPath",
  skillPathName: "skillPathName",
  skillPathSkill: "skillPathSkill",
  skillPathLine: "skillPathLine",
  skillPathIcon: "skillPathIcon",
  pointsCounter: "pointsCounter",
  pointsCounterPoints: "pointsCounterPoints",
  talentTree: "talentTree",
  talentTreeRules: "talentTreeRules",
  talentTreeReset: "talentTreeReset",
};
